services:
  # Factory
  Horlyk\Bundle\FetchXmlBundle\Services\Factory\QueryBuilderFactory:
    arguments:
      - "%horlyk_fetch_xml.use_pager%"
      - "%horlyk_fetch_xml.items_per_page%"
      - "%horlyk_fetch_xml.attribute_aliases_as_names%"
      - "%horlyk_fetch_xml.attribute_alias_prefix%"

  Horlyk\Bundle\FetchXmlBundle\Services\Factory\QueryBuilderFactoryInterface: '@Horlyk\Bundle\FetchXmlBundle\Services\Factory\QueryBuilderFactory'

  # Builder
  Horlyk\Bundle\FetchXmlBundle\Services\QueryBuilder:
    factory: ['@Horlyk\Bundle\FetchXmlBundle\Services\Factory\QueryBuilderFactory', 'createBuilder']

  Horlyk\Bundle\FetchXmlBundle\Services\QueryBuilderInterface: '@Horlyk\Bundle\FetchXmlBundle\Services\QueryBuilder'

